-- Drop all tables in the correct order to avoid foreign key constraints
DROP TABLE IF EXISTS "OrderItem" CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS "OrderWindow" CASCADE;
DROP TABLE IF EXISTS "DayStat" CASCADE;
DROP TABLE IF EXISTS "MenuItemSize" CASCADE;
DROP TABLE IF EXISTS "MenuItem" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "Table" CASCADE;
DROP TABLE IF EXISTS "Staff" CASCADE;
DROP TABLE IF EXISTS "Setting" CASCADE;
DROP TABLE IF EXISTS "Restaurant" CASCADE;
DROP TABLE IF EXISTS "Payment" CASCADE;
DROP TABLE IF EXISTS "AuditLog" CASCADE;
DROP TABLE IF EXISTS "OwnerLoginAttempt" CASCADE;
DROP TABLE IF EXISTS "SiteSetting" CASCADE;
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;

-- Recreate the schema
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";